# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41d064b5f31070dda5e27de286bd2fb1571a5ee3be580ba3bda68dcd222638529eb7a2f56be04ebc079584bd11d521dbd1be5692f4eea6851a297a05db50fd20

test:
  secret_key_base: 557538b13509120042a9f89a3c5cefd8a29109845568b9ae3fc913a5d05b4e6dfdf2b686a978bc885bc652cd8d75a90fdbbbd0f407d4d9479fcf4da7ed876f7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
